<a href="https://colab.research.google.com/github/diegovilarim/python/blob/main/Aula01Modulo03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
meuArray = np.array(minhaLista)
meuArray
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [ ]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
type(array3)

numpy.ndarray

In [ ]:
array3.dtype

dtype('int64')

In [ ]:
vetor1 = np.array([0, 1, 2, 3, 4])

In [ ]:
vetor1[3]

3

In [ ]:
vetor1[0:2]

array([0, 1])

In [ ]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
#minhaMatriz = np.array([1,2,3,[4,5,6]])
#print(minhaMatriz)

[1 2 3 list([4, 5, 6])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  """Entry point for launching an IPython kernel.


In [ ]:
minhaLista = [[13,81,22], [0,34,59],[21,48,94]]

In [ ]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [ ]:
x = np.zeros(3)
x

array([0., 0., 0.])

In [ ]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [ ]:
w = np.ones((4,4))*8
w

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [ ]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
y = np.eye(5, dtype = int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.shape(minhaMatriz)

(3, 3)

In [ ]:
minhaMatriz.shape

(3, 3)

In [ ]:
type (minhaMatriz)

numpy.matrix

In [ ]:
minhaMatriz.dtype

dtype('int64')

In [ ]:
minhaMatriz[2,1]

48

In [ ]:
print(minhaMatriz[0,:])

[[13 81 22]]


In [ ]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [ ]:
np.sum(meuArray)

36

In [ ]:
np.prod(meuArray)

0

In [ ]:
np.cumsum(meuArray)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
meuArray.min()

0

In [ ]:
meuArray.max()

8

In [ ]:
np.mean(meuArray)

4.0

In [ ]:
np.median(meuArray)

4.0

In [ ]:
np.var(meuArray)

6.666666666666667

In [ ]:
np.std(meuArray)

2.581988897471611

In [ ]:
array10 = np.arange(20)

print(np.arange(1,20,2))
print(np.mean(array10))
print(np.sum(array10))

[ 1  3  5  7  9 11 13 15 17 19]
9.5
190


In [ ]:
array10[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
array10[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])